### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jessmhoehner**
I noticed the links for a couple of the points under "on worflow:" had been updated by the authors of the book so I updated them here.

### CODE REVIEW

**Comment by baileyb0t** [comment]
Excellent, thank you!

**Review by baileyb0t — COMMENTED** [review]
tested links and made sure they worked and went to the expected pages

**Comment by baileyb0t** [comment]
@vm-wylbur oops, closed instead of just reviewing this. feel free to re-open if needed!

**Comment by vm-wylbur** [comment]
looks great, thanks to both of you! I think ok to close.

**Pull request merged**
